# Convenient shortcuts for local development

build:
	docker build --tag sytizen-server .

# Default port 5000 is in use on Ventura Macs
# 7355 chosen for TESS
run:
	docker run -d -p 7355:7355 sytizen-server

# stop:
# 	docker 