create table
    public."missions" (
        id bigint generated by default as identity,
        user uuid null,
        time_of_completion timestamp with time zone null,
        mission bigint null, -- I'm thinking that we have a grouping i.e. group# followed by "000" and then mission #
        configuration jsonb null, -- This will house the information on how the achievement was completed (e.g. what item id in `inventory` table was used to complete the mission)
        constraint missions_pkey primary key (id),
        constraint missions_user_fkey foreign key (user) references profiles (id)
    ) tablespace pg_default;