create table
  public."anomalies" (
    id bigint generated by default as identity,
    content text null,
    "ticId" text null,
    anomalyType text null,
    type text null,
    radius double precision null,
    mass double precision null,
    density double precision null,
    gravity double precision null,
    "temperatureEq" double precision null,
    temperature double precision null,
    smaxis double precision null,
    orbital_period double precision null, 
    classification_status text null,
    avatar_url text null,
    created_at timestamp with time zone not null default now(),
    deepnote text null,
    lightkurve text null,
    configuration jsonb null, -- Adding the new JSONB column
    constraint basePlanets_pkey primary key (id)
) tablespace pg_default;
