create table
    public."sectors" (
        id bigint generated by default as identity,
        anomaly bigint null,
        deposit bigint null, -- Points to item (`inventoryITEMS`) // mineral deposit
        constraint sectors_pkey primary key (id),
        constraint sectors_anomaly_fkey foreign key (anomaly) references "anomalies" (id)
    ) tablespace pg_default;
