create table public.user_anomalies (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    anomaly_id bigint not null,
    ownership_date timestamp with time zone not null default now(),
    constraint user_anomalies_user_fkey foreign key (user_id) references profiles (id) on delete cascade,
    constraint user_anomalies_anomaly_fkey foreign key (anomaly_id) references anomalies (id) on delete cascade
) tablespace pg_default;
 